// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExperimentStatus
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSExperimentStatus.6289cb33-1c43-4f87-a523-cc223e36cadf";
        public const string Name = "VSExperimentStatus";
        public const string Description = @"Show VS Experimental Flags";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Chris Sienkiewicz";
        public const string Tags = "";
    }
}
