// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace VSExperimentStatus
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSExperimentStatusString = "3d5b0bfa-b9b7-4429-852e-65c1b1743183";
        public static Guid VSExperimentStatus = new Guid(VSExperimentStatusString);

        public const string UIProviderString = "B7C47946-8A7C-42C9-9FFF-466A57CB4DC3";
        public static Guid UIProvider = new Guid(UIProviderString);

        public const string UIButtonString = "D0C6A713-6562-45FE-A6E2-C1F01763D4F5";
        public static Guid UIButton = new Guid(UIButtonString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
    }
}